<?php

/**
 * Implements hook_migrate_api().
 */
function migrate_eu_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'EuUser' => array(
        'class_name' => 'EuUserMigration',
      ),
      'EuNews' => array(
        'class_name' => 'EuNewsMigration',
      ),
      'EuEvent' => array(
        'class_name' => 'EuEventMigration',
      ),
      'EuComment' => array(
        'class_name' => 'EuCommentMigration',
      ),
      'EuDocument' => array(
        'class_name' => 'EuDocumentMigration',
      ),
    ),
  );

  return $api;
}
