<?php

/**
 * Implements hook_migrate_api().
 */
function migrate_eu_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'EuUser' => array(
        'class_name' => 'EuUserMigration',
      ),
      'EuNews' => array(
        'class_name' => 'EuNewsMigration',
      ),
      'EuEvent' => array(
        'class_name' => 'EuEventMigration',
      ),
      'EuComment' => array(
        'class_name' => 'EuCommentMigration',
      ),
      'EuDocument' => array(
        'class_name' => 'EuDocumentMigration',
      ),
      'EuProfile' => array(
        'class_name' => 'EuProfileMigration',
      ),
      'EuMembership' => array(
        'class_name' => 'EuMembershipMigration',
      ),
    ),
  );

// Patch for the EuMembership migration. Apply before start process.
// $ret = array();
// db_add_field($ret, 'migrate_map_eumembership', 'destid2', array('type' => 'int', 'length' => 11));

  return $api;
}
